title: Environmental Subsystem
icon: mdi:access-point
path: environmental
cards:
  - type: custom:mini-graph-card
    icon: mdi:thermometer
    name: INDOOR TEMPERATURE
    hours_to_show: 12
    points_per_hour: 2
    entities:
      - entity: sensor.family_room_motion_sensor_air_temperature
        name: Dining Room
      - entity: sensor.dining_room_temperature
        name: Target
      - entity: sensor.master_bedroom_dresser_motion_sensor_air_temperature
        name: Master Bedroom
      - entity: sensor.kitchen_motion_sensor_air_temperature
        name: Kitchen
      - entity: sensor.water_heater_flood_sensor_air_temperature
        name: Mechanical Room
    card_mod:
      class: header

  - type: statistics-graph
    title: 'Temperature'
    chart_type: line
    days_to_show: 1
    stat_types:
      - mean
    period: hour
    entities:
      - entity: sensor.weatherflow_air_temperature
        name: Outside
      - entity: sensor.master_bedroom_dresser_motion_sensor_air_temperature
        name: Upstairs
      - entity: sensor.mean_main_floor_temperature
        name: Main Floor
      - entity: sensor.mean_basement_temperature
        name: Basement
    card_mod:
      class: middle

  - type: vertical-stack
    cards:
      - type: markdown
        card_mod:
          class: header
        content: '# Batteries'
      - type: custom:auto-entities
        card:
          type: entities
          # title: Batteries
          show_header_toggle: false
          card_mod:
            class: middle
        filter:
          include:
            - domain: sensor
              entity_id: "*battery_level"

  - type: vertical-stack
    cards:
      - type: markdown
        content: >
          ## Workroom Closet
        card_mod:
          class: header
      - type: custom:mini-graph-card
        name: HUMIDITY
        entities:
          - entity: sensor.wirelesstag_workroom_closet_humidity
            name: HUMIDITY
            color: blue
        show:
          legend: false
          labels: true
        card_mod:
          class: middle
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: TEMPERATURE
            entities:
              - entity: sensor.wirelesstag_workroom_closet_temperature
                name: TEMPERATURE
                color: red
            show:
              graph: bar
              legend: false
            card_mod:
              class: middle
          - type: sensor
            name: BATTERY
            entity: sensor.wirelesstag_workroom_closet_battery_level
            graph: none
            card_mod:
              class: middle-blank

  - type: vertical-stack
    cards:
      - type: markdown
        content: >
          ## Humidor
        card_mod:
          class: header
      - type: custom:mini-graph-card
        name: HUMIDITY
        entities:
          - entity: sensor.wirelesstag_humidor_humidity
            name: HUMIDITY
            color: blue
        show:
          legend: false
          labels: true
        card_mod:
          class: middle
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: TEMPERATURE
            entities:
              - entity: sensor.wirelesstag_humidor_temperature
                name: TEMPERATURE
                color: red
            show:
              graph: bar
              legend: false
            card_mod:
              class: middle
          - type: sensor
            name: BATTERY
            entity: sensor.wirelesstag_humidor_battery_level
            graph: none
            card_mod:
              class: middle-blank

  - type: vertical-stack
    cards:
      - type: markdown
        content: >
          ## Wine Rack
        card_mod:
          class: header
      - type: custom:mini-graph-card
        name: HUMIDITY
        entities:
          - entity: sensor.wirelesstag_wine_rack_humidity
            name: HUMIDITY
            color: blue
        show:
          legend: false
          labels: true
        card_mod:
          class: middle
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: TEMPERATURE
            entities:
              - entity: sensor.wirelesstag_wine_rack_temperature
                name: TEMPERATURE
                color: red
            show:
              graph: bar
              legend: false
            card_mod:
              class: middle
          - type: sensor
            name: BATTERY
            entity: sensor.wirelesstag_wine_rack_battery_level
            graph: none
            card_mod:
              class: middle-blank
