title: Settings
icon: mdi:tune
path: system
cards:
  - type: entities
    title: System
    show_header_toggle: false
    entities:
      - sensor.date
      - sensor.time
      - sensor.processor_use
      - sensor.disk_use_percent
      - sensor.memory_use_percent
      - sensor.last_boot
      - sensor.network_in_eth0
      - sensor.network_out_eth0
      - sensor.load_1m
      - sensor.load_5m
      - sensor.load_15m
      - sensor.current_version

  - type: custom:mini-graph-card
    name: Network
    icon: mdi:server
    entities:
      - entity: sensor.speedtest_download
        name: DOWNLOAD
      - entity: sensor.speedtest_upload
        name: UPLOAD
      - entity: sensor.speedtest_ping
        name: PING
        y_axis: secondary
