### ui-lovelace.yaml
# https://www.home-assistant.io/lovelace

####################################################
#                                                  #
#                 Lovelace UI                      #
#                                                  #
####################################################

title: Otteropolis

# Exclude entities from "Unused entities" view
excluded_entities:

decluttering_templates:
  camera_button:
    card:
      type: custom:button-card
      entity: '[[entity]]'
      icon: '[[icon]]'
      show_state: false
      show_icon: true
      show_name: false
      tap_action:
        action: toggle
      style: |
        ha-card {
          # font-family: 'Open Sans', sans-serif;
          padding-top: 10px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }

  nest_button:
    default:
      - show_state: true
      - show_name: false
    card:
      type: custom:button-card
      entity: '[[entity]]'
      show_last_changed: true
      show_state: '[[show_state]]'
      show_icon: true
      show_name: '[[show_name]]'
      name: '[[name]]'
      state: '[[state]]'
      tap_action:
        action: more-info
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        ha-icon {
          width: 60% !important;
        }
        img {
          width: 100%;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }
        #label {
          font-size: 70%;
        }

  nest_picture_button:
    card:
      type: custom:button-card
      entity: '[[entity]]'
      show_state: true
      show_icon: true
      show_name: false
      show_entity_picture: true
      entity_picture: '[[entity_picture]]'
      tap_action:
        action: more-info
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        img {
          width: 100% !important;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }

views:
  - !include lovelace/home_view.yaml
  - !include lovelace/lights_view.yaml
  - !include lovelace/rooms_view.yaml
  - !include lovelace/camera_view.yaml
  - !include lovelace/media_view.yaml
  - !include lovelace/sensor_view.yaml
  - !include lovelace/automations_view.yaml
  - !include lovelace/settings_view.yaml

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
