### ui-lovelace.yaml
# https://www.home-assistant.io/lovelace

####################################################
#                                                  #
#                 Lovelace UI                      #
#                                                  #
####################################################

title: Otteropolis

# Exclude entities from "Unused entities" view
excluded_entities:

views:
  - !include lovelace/home_view.yaml
  - !include lovelace/lighting_view.yaml
  - !include lovelace/surveillance_view.yaml
  - !include lovelace/media_view.yaml
  - !include lovelace/sensor_view.yaml
  - !include lovelace/automations_view.yaml
  - !include lovelace/settings_view.yaml

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
