################################################################
## Packages / Airthings
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'airthings'

    ################################################
    ## Sensor
    ################################################

    sensor.basement_radon_pcil:
      <<: *customize
      friendly_name: "Basement Radon"
      icon: mdi:radioactive

################################################
## Sensor
################################################

template:
  - sensor:
    - default_entity_id: sensor.basement_radon_pcil:
      unit_of_measurement: 'pCi/L'
      state: "{{ (states('sensor.basement_radon') | float / 37) | round(2) }}"
