################################################################
## Packages / Alarm
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'alarm'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Alarm Control Panel
    ################################################

    alarm_control_panel.alarm_system:
      <<: *customize
      friendly_name: "Alarm System"

    ################################################
    ## Automation
    ################################################

    automation.persistence_publish_alarm_control_panel:
      <<: *customize
      friendly_name: "Persistence Publish (Alarm System)"
      icon: mdi:alarm

    automation.persistence_subscribe_alarm_control_panel:
      <<: *customize
      friendly_name: "Persistence Subscribe (Alarm System)"
      icon: mdi:alarm

    automation.alarm_startup_state:
      <<: *customize
      friendly_name: "Arm Alarm on System Startup"
      icon: mdi:alarm

    automation.trigger_alarm_on_binary_sensor:
      <<: *customize
      friendly_name: "Trigger Alarm on Binary Sensor"

    automation.alarm_triggered_notification:
      <<: *customize
      friendly_name: "Send Notification on Alarm Trigger"
      persistent: true
      icon: mdi:message-text

    trigger_notification_on_sensor_tamper:
      <<: *customize
      friendly_name: "Send Notification on Tamper"
      persistent: true
      icon: mdi:message-text

################################################
## Alarm Control Panel
################################################

alarm_control_panel:
  - platform: manual
    name: alarm_system
    code: !secret alarm_code
    arming_time: 45
    delay_time: 45
    trigger_time: 120
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0
    armed_night:
      arming_time: 0
      delay_time: 0
    armed_custom_bypass:
      arming_time: 0
      delay_time: 0

################################################
## Automation
################################################

automation:
  - alias: persistence_publish_alarm_control_panel
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_system
    condition:
      - condition: template
        value_template: "{{ trigger.to_state is not none }}"
      - condition: template
        value_template: "{{ trigger.to_state.attributes is not none }}"
      - condition: template
        value_template: "{{ trigger.from_state is not none }}"
      - condition: template
        value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
      - condition: template
        value_template: "{{ trigger.to_state.state != 'pending' }}"
      - condition: template
        value_template: "{{ trigger.to_state.state != 'triggered' }}"
    action:
      - service: mqtt.publish
        data_template:
          topic: "homeassistant/alarm_control_panel/alarm_system"
          payload: "{{ trigger.to_state.state }}"
          retain: true

  - alias: persistence_subscribe_alarm_control_panel
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: homeassistant/alarm_control_panel/alarm_system
    condition:
      - condition: template
        value_template: "{{ not is_state('alarm_control_panel.alarm_system', trigger.payload) }}"
    action:
      - service_template: >-
          {% if trigger.payload == 'armed_home' %}
            alarm_control_panel.alarm_arm_home
          {% elif trigger.payload == 'armed_night' %}
            alarm_control_panel.alarm_arm_night
          {% elif trigger.payload == 'disarmed' %}
            alarm_control_panel.alarm_disarm
          {% elif trigger.payload == 'armed_custom_bypass' %}
            alarm_control_panel.alarm_arm_custom_bypass
          {% else %}
            alarm_control_panel.alarm_arm_away
          {% endif %}
        entity_id: alarm_control_panel.alarm_system
        data:
          code: !secret alarm_code

  - alias: trigger_alarm_on_binary_sensor
    trigger:
      - platform: state
        entity_id: binary_sensor.entrance_front_door_sensor
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.garage_door_sensor
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.guest_closet_door_access_control_door_window_open
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.guest_storage_door_access_control_door_window_open
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.julias_closet_door_access_control_door_window_open
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kitchen_motion_sensor
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor_home_security_motion_detected
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion_sensor_home_security_motion_detected
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.michaels_closet_door_access_control_door_window_open
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm_system
        state: 'armed_away'
    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm_system
      data:
        code: !secret alarm_code

  - alias: alarm_triggered_notification
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_system
        to: 'triggered'
    action:
      - service: notify.sms
        data_template:
          message: >
            Alarm was triggered on:
            {% for state in states.binary_sensor -%}
              {% if state.state == 'on' and state.entity_id in ['binary_sensor.entrance_front_door_sensor', 'binary_sensor.garage_door_sensor', 'binary_sensor.guest_closet_door_access_control_door_window_open', 'binary_sensor.guest_storage_door_access_control_door_window_open', 'binary_sensor.julias_closet_door_access_control_door_window_open',
              'binary_sensor.kitchen_motion_sensor', 'binary_sensor.living_room_motion_sensor_home_security_motion_detected', 'binary_sensor.master_bedroom_motion_sensor_home_security_motion_detected', 'binary_sensor.michaels_closet_door_access_control_door_window_open'] %}
                {{ state.name }}
              {%- endif -%}
            {%- endfor -%}
          target:
            - !secret mobile_michael

  - alias: trigger_notification_on_sensor_tamper
    trigger:
      - platform: state
        entity_id: binary_sensor.garage_door_home_security_tampering_cover_removed
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.guest_closet_door_home_security_tampering_cover_removed
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.guest_storage_door_home_security_tampering_cover_removed
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.julias_closet_door_home_security_tampering_cover_removed
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.laundry_room_flood_sensor_home_security_tampering_cover_removed
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor_home_security_tampering_cover_removed
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion_sensor_home_security_tampering_cover_removed
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.michaels_closet_door_home_security_tampering_cover_removed
        from: 'off'
        to: 'on'
    action:
      - service: notify.mobile_app_michael_iphone
        data_template:
          data:
            title: Tamper Notification
          message: >
            Cover removed from {{ trigger.to_state.attributes.friendly_name }}!
      - service: persistent_notification.create
        data_template:
          title: Tamper Notification
          message: >
            Cover removed from {{ trigger.to_state.attributes.friendly_name }}!
