################################################################
## Packages / B-hyve
## https://github.com/sebr/bhyve-home-assistant
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'bhyve'

################################################
## Bhyve
################################################

bhyve:
  username: !secret bhyve_username
  password: !secret bhyve_password

################################################
## Sensor
################################################

sensor:
  - platform: bhyve

################################################
## Switch
################################################

switch:
  - platform: bhyve
