################################################################
## Packages / Cloud
## https://www.home-assistant.io/components/cloud/
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'cloud'

################################################
## Cloud
################################################

cloud:
  alexa:
    filter:
      include_entities:
        - automation.master_bedroom_motion
        - automation.living_room_motion
        - binary_sensor.basement_stair_closet_door_window_door_is_open
        - binary_sensor.basement_sump_pump_closet_door_window_door_is_open
        - binary_sensor.laundry_room_door_window_door_is_open
        - binary_sensor.workroom_closet_door_window_door_is_open
        - binary_sensor.kitchen_motion_sensor_motion_detection
        - binary_sensor.water_heater_flood_sensor_water_leak_detected
        - binary_sensor.family_room_motion_sensor_motion_detection
        - binary_sensor.master_bedroom_dresser_motion_sensor_motion_detection
        - switch.christmas_tree_switch
        - switch.front_porch_outdoor_double_plug
        - switch.front_porch_outdoor_double_plug_2
        - switch.master_bedroom_outlet_switch
      exclude_domains:
        - alert
        - automation
        - binary_sensor
        - camera
        - group
        - input_boolean
        - media_player
        - number
        - script
        - switch
      exclude_entities:
        - light.dining_room_hutch_light_light_ring
        - light.exterior_lights
        - light.interior_lights
        - light.office_bookshelf_lamp_light_ring
        - light.christmas_tree_switch
        - sensor.mean_basement_temperature
        - sensor.mean_main_floor_temperature
        - sensor.mnemosyne_average_disk_temp
        - sensor.mnemosyne_drive_1_temperature
        - sensor.mnemosyne_drive_2_temperature
        - sensor.mnemosyne_volume_2_average_disk_temp
        - sensor.mnemosyne_drive_3_temperature
        - sensor.mnemosyne_drive_4_temperature
        - sensor.mnemosyne_temperature
        - sensor.mnemosyne_temperature_2
        - sensor.mnemosyne_temperature_3
        - sensor.mnemosyne_temperature_4
        - sensor.mnemosyne_temperature_5
        - sensor.wirelesstag_desktop_humidor_temperature
        - sensor.wirelesstag_diamond_crown_humidor_temperature
        - sensor.weatherflow_air_temperature
        - sensor.weatherflow_dewpoint
        - sensor.weatherflow_feels_like_temperature
        - sensor.weatherflow_delta_t
        - sensor.weatherflow_heat_index
        - sensor.weatherflow_wet_bulb_temperature
        - sensor.weatherflow_wind_chill
    entity_config:
      sensor.family_room_motion_sensor_air_temperature:
        name: Family Room Temperature
        display_categories: TEMPERATURE_SENSOR
      sensor.kitchen_motion_sensor_air_temperature:
        name: Kitchen Temperature
        display_categories: TEMPERATURE_SENSOR
      sensor.master_bedroom_dresser_motion_sensor_air_temperature:
        name: Bedroom Temperature
        display_categories: TEMPERATURE_SENSOR
      sensor.water_heater_flood_sensor_air_temperature:
        name: Mechanical Room Temperature
        display_categories: TEMPERATURE_SENSOR
      sensor.wirelesstag_wine_rack_temperature:
        name: Wine Rack Temperature
        display_categories: TEMPERATURE_SENSOR
