################################################################
## Packages / Cloud
## https://www.home-assistant.io/components/cloud/
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'cloud'

################################################
## Cloud
################################################

cloud:
  alexa:
    filter:
      include_entities:
        - automation.master_bedroom_motion
        - automation.living_room_motion
        - binary_sensor.front_door_access_control_window_door_is_open
        - binary_sensor.guest_closet_door_access_control_door_window_open
        - binary_sensor.guest_storage_door_access_control_window_door_is_open
        - binary_sensor.julias_closet_door_access_control_window_door_is_open
        - binary_sensor.kitchen_motion_sensor
        - binary_sensor.laundry_room_flood_sensor_water_alarm_water_leak_detected
        - binary_sensor.living_room_motion_sensor_home_security_motion_detection
        - binary_sensor.master_bedroom_motion_sensor_home_security_motion_detection
        - binary_sensor.michaels_closet_door_access_control_window_door_is_open
      exclude_domains:
        - alert
        - automation
        - binary_sensor
        - camera
        - group
        - media_player
        - script
      exclude_entities:
        - light.living_room_bookshelf_lamp_instance_2_level
        - light.living_room_floor_lamp_instance_2_level
        - switch.apple_tv
        - switch.basement_task_light
        - switch.lg_tv
        - switch.mnemosyne_home_mode
        - switch.xbox_one
        - sensor.mnemosyne_drive_1_temperature
        - sensor.mnemosyne_drive_2_temperature
        - sensor.mnemosyne_volume_2_average_disk_temp
        - sensor.mnemosyne_drive_3_temperature
        - sensor.mnemosyne_drive_4_temperature
        - sensor.mnemosyne_temperature
        - sensor.wirelesstag_desktop_humidor_temperature
        - sensor.wirelesstag_diamond_crown_humidor_temperature
        - sensor.dark_sky_temperature
    entity_config:
      sensor.living_room_motion_sensor_air_temperature:
        name: Living Room Temperature
        display_categories: TEMPERATURE_SENSOR
      sensor.kitchen_motion_sensor_air_temperature:
        name: Kitchen Temperature
        display_categories: TEMPERATURE_SENSOR
      sensor.master_bedroom_motion_sensor_air_temperature:
        name: Bedroom Temperature
        display_categories: TEMPERATURE_SENSOR
      sensor.laundry_room_flood_sensor_air_temperature:
        name: Laundry Room Temperature
        display_categories: TEMPERATURE_SENSOR
      sensor.wirelesstag_dungeon_temperature:
        name: Dungeon Temperature
        display_categories: TEMPERATURE_SENSOR
