################################################################
## Packages / Cloud
## https://www.home-assistant.io/components/cloud/
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'cloud'

################################################
## Cloud
################################################

cloud:
  alexa:
    filter:
      include_entities:
        - automation.master_bedroom_motion
        - automation.living_room_motion
      exclude_domains:
        - alert
        - automation
        - group
        - script
      exclude_entities:
        - binary_sensor.living_room_nest_protect_online
        - binary_sensor.living_room_thermostat_fan
        - binary_sensor.living_room_thermostat_has_leaf
        - binary_sensor.living_room_thermostat_is_locked
        - binary_sensor.living_room_thermostat_is_using_emergency_heat
        - binary_sensor.living_room_thermostat_online
        - binary_sensor.otter_den_away
        - binary_sensor.remote_ui
        - media_player.dining_room
        - media_player.living_room
        - media_player.office
        - switch.aeotec_zstick_disco_light
        - switch.basement_task_light
        - sensor.wirelesstag_desktop_humidor_temperature
        - sensor.wirelesstag_diamond_crown_humidor_temperature
        - sensor.dark_sky_temperature
    entity_config:
      sensor.living_room_motion_sensor_temperature:
        name: Living Room Temperature
        display_categories: TEMPERATURE_SENSOR
      sensor.master_bedroom_motion_sensor_temperature:
        name: Bedroom Temperature
        display_categories: TEMPERATURE_SENSOR
      sensor.laundry_room_flood_sensor_temperature:
        name: Laundry Room Temperature
        display_categories: TEMPERATURE_SENSOR
      switch.living_room_bookshelf_lamp:
        display_categories: LIGHT
