################################################################
## Packages / Ecobee
## https://www.home-assistant.io/integrations/ecobee/
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'ecobee'

    ################################################
    ## Climate
    ################################################

    climate.dining_room:
      <<: *customize
      friendly_name: 'Thermostat'
      icon: mdi:thermostat

    ################################################
    ## Script
    ################################################

    script.set_ecobee_away:
      <<: *customize
      friendly_name: Set Ecobee Thermostat Away

    script.set_ecobee_home:
      <<: *customize
      friendly_name: Set Ecobee Thermostat Home

    ################################################
    ## Sensor
    ################################################

    sensor.dining_room_humidity:
      <<: *customize
      friendly_name: Dining Room Humidity
      device_class: humidity

    sensor.dining_room_temperature:
      <<: *customize
      friendly_name: Dining Room Temperature
      device_class: temperature

################################################
## Script
################################################

script:
  set_ecobee_away:
    sequence:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.dining_room
          preset_mode: 'away'

  set_ecobee_home:
    sequence:
      - service: ecobee.resume_program
        data:
          entity_id: climate.dining_room
          resume_all: true
