################################################################
## Packages / Good Morning/Night
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'good_morning_night'

    ################################################
    ## Automation
    ################################################

    automation.auto_morning:
      <<: *customize
      friendly_name: "Auto Morning"
      icon: mdi:robot

    automation.auto_evening:
      <<: *customize
      friendly_name: "Auto Evening"
      icon: mdi:robot

    automation.auto_night_weekday:
      <<: *customize
      friendly_name: "Auto Night (Work Nights)"
      icon: mdi:robot

    automation.auto_night_weekend:
      <<: *customize
      friendly_name: "Auto Night (Weekends & Guest Mode)"
      icon: mdi:robot

    automation.auto_sunrise:
      <<: *customize
      friendly_name: "Auto Sunrise (Weekdays)"
      icon: mdi:robot

    ################################################
    ## Input DateTime
    ################################################

    input_datetime.auto_sunrise_time:
      <<: *customize
      friendly_name: "Auto Sunrise Time"
      icon: mdi:weather-sunset-up

    ################################################
    ## Script
    ################################################

    script.good_evening:
      <<: *customize
      friendly_name: "Good Evening"
      icon: mdi:weather-sunset

    script.good_night:
      <<: *customize
      friendly_name: "Good Night"
      icon: mdi:weather-night

    script.sunrise:
      <<: *customize
      friendly_name: "Sunrise"
      icon: mdi:weather-sunset-up

################################################
## Automation
################################################

automation:
  - alias: auto_morning
    initial_state: true
    trigger:
      - platform: sun
        event: sunrise
        offset: '-00:30:00'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm_system
        state: 'armed_night'
    action:
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.alarm_system
        data:
          code: !secret alarm_code

  - alias: auto_evening
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:30:00'
      - platform: state
        entity_id: alarm_control_panel.alarm_system
        to: 'armed_home'
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
          after_offset: '-00:30:00'
        - condition: or
          conditions:
            - condition: state
              entity_id: alarm_control_panel.alarm_system
              state: 'armed_home'
            - condition: state
              entity_id: alarm_control_panel.alarm_system
              state: 'disarmed'
    action:
      - service: script.good_evening

  - alias: auto_night_weekday
    trigger:
      - platform: time
        at: '23:30:00'
    condition:
      condition: and
      conditions: 
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - sun
        - condition: state
          entity_id: alarm_control_panel.alarm_system
          state: 'armed_home'
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'off'
    action:
      - service: alarm_control_panel.alarm_arm_night
        entity_id: alarm_control_panel.alarm_system
        data:
          code: !secret alarm_code

  - alias: auto_night_weekend
    trigger:
      - platform: time
        at: '03:00:00'
    condition:
      condition: and
      conditions: 
        - condition: state
          entity_id: alarm_control_panel.alarm_system
          state: 'armed_home'
    action:
      - service: alarm_control_panel.alarm_arm_night
        entity_id: alarm_control_panel.alarm_system
        data:
          code: !secret alarm_code

  - alias: manual_night
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_system
        to: 'armed_night'
        from: 'armed_home'
      - platform: state
        entity_id: alarm_control_panel.alarm_system
        to: 'armed_night'
        from: 'disarmed'
    action:
      - service: script.good_night

  - alias: auto_sunrise
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (state_attr('input_datetime.auto_sunrise_time', 'timestamp') | int | timestamp_custom('%H:%M', false)) }}"
    condition:
      condition: and
      conditions: 
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: or
          conditions:
            - condition: state
              entity_id: alarm_control_panel.alarm_system
              state: 'armed_home'
            - condition: state
              entity_id: alarm_control_panel.alarm_system
              state: 'armed_night'
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'off'
    action:
      - service: script.sunrise

################################################
## Input DateTime
################################################

input_datetime:
  auto_sunrise_time:
    has_date: false
    has_time: true

################################################
## Script
################################################

script:
  good_evening:
    sequence:
      - service: automation.turn_on
        data:
          entity_id:
            - automation.living_room_motion
            - automation.master_bedroom_motion

  good_night:
    sequence:
      - service: automation.turn_off
        data:
          entity_id:
            - automation.living_room_motion
            - automation.master_bedroom_motion

      - service: script.all_interior_lights_off

  sunrise:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.nightstand_lamp
          xy_color: [0.67,0.39]
          brightness: 1
      - delay:
          seconds: 1
      - service: light.turn_on
        data:
          entity_id: light.nightstand_lamp
          xy_color: [0.65,0.41]
          brightness: 85
          transition: 600
      - delay:
          seconds: 600
      - service: light.turn_on
        data:
          entity_id: light.nightstand_lamp
          xy_color: [0.60,0.40]
          brightness: 170
          transition: 600
      - delay:
          seconds: 600
      - service: light.turn_on
        data:
          entity_id: light.nightstand_lamp
          xy_color: [0.48,0.40]
          brightness: 255
          transition: 600
