################################################################
## Packages / Homekit
## https://www.home-assistant.io/components/homekit/
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'homekit'

################################################
## Homekit
################################################

homekit:
  filter:
    exclude_domains:
      - automation
      - binary_sensor
      - camera
      - device_tracker
      - input_select
      - sensor
      - script
      - remote
    exclude_entities:
      - light.dining_room_spot
      - light.dresser_lamp
      - light.guest_bedroom_storage
      - light.julias_closet
      - light.living_room_bookshelf_lamp_instance_2_level
      - light.living_room_floor_lamp_instance_2_level
      - light.michaels_closet
      - light.nightstand_lamp
      - light.table_light
      - light.task_light
      - media_player.living_room_tv
      - switch.apple_tv
      - switch.basement_task_light
      - switch.garage_door_signaling_state_audible
      - switch.garage_door_signaling_state_visual
      - switch.lg_tv
      - switch.mnemosyne_home_mode
      - switch.xbox_one
    include_entities:
      - automation.master_bedroom_motion
      - automation.living_room_motion
      - binary_sensor.front_door_access_control_window_door_is_open
      - binary_sensor.guest_closet_door_access_control_window_door_is_open
      - binary_sensor.guest_storage_door_access_control_window_door_is_open
      - binary_sensor.julias_closet_door_access_control_window_door_is_open
      - binary_sensor.kitchen_motion_sensor_motion
      - binary_sensor.laundry_room_flood_sensor_water_alarm_water_leak_detected
      - binary_sensor.living_room_motion_sensor_home_security_motion_detection
      - binary_sensor.master_bedroom_motion_sensor_home_security_motion_detection
      - binary_sensor.michaels_closet_door_access_control_window_door_is_open
  entity_config:
    alarm_control_panel.alarm_system:
      code: !secret alarm_code
