################################################################
## Packages / Homekit
## https://www.home-assistant.io/components/homekit/
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'homekit'

################################################
## Homekit
################################################

homekit:
  filter:
    exclude_domains:
      - automation
      - binary_sensor
      - camera
      - device_tracker
      - input_select
      - media_player
      - person
      - scene
      - select
      - sensor
      - script
      - remote
    exclude_entities:
      - light.christmas_tree_switch
      - light.dining_room_hutch_light_light_ring
      - light.office_bookshelf_lamp_light_ring
      - switch.apple_tv
      - switch.backyard_smart_hose_timer_rain_delay
      - switch.backyard_smart_hose_timer_program_a
      - switch.backyard_smart_hose_timer_program_b
      - switch.backyard_smart_hose_timer_program_c
      - switch.front_yard_smart_hose_timer_rain_delay
      - switch.front_yard_smart_hose_timer_program_a
      - switch.front_yard_smart_hose_timer_program_b
      - switch.front_yard_smart_hose_timer_program_c
      - switch.garage_door_signaling_state_audible
      - switch.garage_door_signaling_state_visual
      - switch.lg_tv
      - switch.living_room_harmony_hub_listen_to_living_room_sonos
      - switch.living_room_harmony_hub_watch_smart_tv
      - switch.mnemosyne_home_mode
      - switch.xbox_one
    include_entities:
      - automation.master_bedroom_motion
      - automation.living_room_motion
      - binary_sensor.basement_stair_closet_door_window_door_is_open
      - binary_sensor.basement_sump_pump_closet_door_window_door_is_open
      - binary_sensor.laundry_room_door_window_door_is_open
      - binary_sensor.workroom_closet_door_window_door_is_open
      - binary_sensor.kitchen_motion_sensor_motion_detection
      - binary_sensor.master_bedroom_dresser_motion_sensor_motion_detection
      - binary_sensor.water_heater_flood_sensor_water_leak_detected
      - binary_sensor.family_room_motion_sensor_motion_detection
      - script.good_night
      - sensor.family_room_motion_sensor_air_temperature
      - sensor.family_room_motion_sensor_illuminance
      - sensor.kitchen_motion_sensor_air_temperature
      - sensor.kitchen_motion_sensor_illuminance
      - sensor.master_bedroom_dresser_motion_sensor_air_temperature
      - sensor.master_bedroom_dresser_motion_sensor_humidity
      - sensor.master_bedroom_dresser_motion_sensor_illuminance
      - sensor.water_heater_flood_sensor_air_temperature
  entity_config:
    alarm_control_panel.alarm_system:
      code: !secret alarm_code
