################################################################
## Packages / House Mode
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'house_mode'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.auto_away:
      <<: *customize
      friendly_name: "Auto Away"
      persistent: true
      icon: mdi:robot

    automation.auto_home:
      <<: *customize
      friendly_name: "Auto Home"
      persistent: true
      icon: mdi:robot

    ################################################
    ## Input Boolean
    ################################################

    input_boolean.guest_mode:
      <<: *customize
      friendly_name: "Guest Mode"
      icon: mdi:account

    ################################################
    ## Script
    ################################################

    script.all_lights_off:
      <<: *customize
      friendly_name: Turn All Lights Off

################################################
## Input Boolean
################################################

input_boolean:
  guest_mode:

################################################
## Automation
################################################

automation:
  - alias: auto_away
    trigger:
      - platform: state
        entity_id: sensor.household
        to: 'Away'
      - platform: state
        entity_id: sensor.household
        to: 'Vacation'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: alarm_control_panel.alarm_system
          state: 'armed_home'
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'off'
    action:
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.alarm_system
        data:
          code: !secret alarm_code
      - service: script.all_lights_off
      - service: script.set_nest_away
      - service: surveillance_station.set_home_mode
        data:
          home_mode: 'away'

  - alias: auto_home
    trigger:
      - platform: state
        entity_id: sensor.household
        to: 'Arriving'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ trigger.from_state.state == 'Away' or trigger.from_state.state == 'Vacation' }}"
        - condition: template
          value_template: "{{ not is_state('alarm_control_panel.alarm_system', 'armed_home') and not is_state('alarm_control_panel.alarm_system', 'disarmed') }}"
    action:
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.alarm_system
        data:
          code: !secret alarm_code
      - service: script.set_nest_home
      - service: surveillance_station.set_home_mode
        data:
          home_mode: 'home'

################################################
## Script
################################################

script:
  all_lights_off:
    sequence:
      - service: script.light_control
        data:
          entity_id: all
          state: 'off'
          transition: 5
      - service: switch.turn_off
        data:
          entity_id: switch.basement_task_light
