################################################################
## Packages / HTTP
## https://home-assistant.io/components/http/
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'http'

################################################
## HTTP
################################################

http:
  cors_allowed_origins:
      - https://google.com
      - https://www.home-assistant.io
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.7
  ip_ban_enabled: true
  login_attempts_threshold: 5
