################################################################
## Packages / iOS
## https://www.home-assistant.io/components/ios/
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'mobile_app'

    ################################################
    ## Automation
    ################################################

    automation.notify_ios_app:
      <<: *customize
      friendly_name: "Notify iOS App"
      persistent: true
      icon: mdi:message-text

    automation.sound_alarm:
      <<: *customize
      friendly_name: "Sound Alarm"
      persistent: true
      icon: mdi:message-text

################################################
## Automation
################################################

automation:
  - alias: notify_ios_app
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_system
        to: 'triggered'
    action:
      service: notify.mobile_app_michael_iphone
      data:
        message: "Something happened at home!"

  - alias: sound_alarm
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: SOUND_ALARM
    action:
      - service: script.sonos_say
        data:
          sonos_entity: media_player.living_room
          volume: 0.6
          message: 'Intruder Alert!'
          delay: '00:00:05'
