################################################################
## Packages / MQTT
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'mqtt'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

################################################
## MQTT
################################################

mqtt:
  birth_message:
    topic: 'home-assistant/status'
    payload: 'online'
  will_message:
    topic: 'home-assistant/status'
    payload: 'offline'
