################################################################
## Packages / MQTT
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'mqtt'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

################################################
## MQTT
################################################

mqtt:
  broker: localhost
#  port: !secret mqtt_port
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#  protocol: '3.1.1'
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
