################################################################
## Packages / Nest
## https://home-assistant.io/components/nest/
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'nest'

    ################################################
    ## Climate
    ################################################

    climate.dining_room:
      <<: *customize
      friendly_name: 'Nest'
      icon: mdi:thermostat

    ################################################
    ## Script
    ################################################

    script.set_nest_away:
      <<: *customize
      friendly_name: Set Nest Thermostat Away

    script.set_nest_home:
      <<: *customize
      friendly_name: Set Nest Thermostat Home

    ################################################
    ## Sensor
    ################################################

    sensor.dining_room_humidity:
      <<: *customize
      friendly_name: Dining Room Humidity
      device_class: humidity

    sensor.dining_room_temperature:
      <<: *customize
      friendly_name: Dining Room Temperature
      device_class: temperature

################################################
## Script
################################################

script:
  set_nest_away:
    sequence:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.dining_room
          preset_mode: eco

  set_nest_home:
    sequence:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.dining_room
          preset_mode: none
