################################################################
## Packages / Nest
## https://home-assistant.io/components/nest/
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'nest'

    ################################################
    ## Binary Sensor
    ################################################

    binary_sensor.living_room_thermostat_fan:
      <<: *customize
      friendly_name: HVAC Fan
      icon: mdi:fan

    binary_sensor.dining_room_thermostat_is_using_emergency_heat:
      <<: *customize
      device_class: problem

    binary_sensor.dining_room_thermostat_online:
      <<: *customize
      device_class: connectivity

    binary_sensor.otter_den_away:
      <<: *customize
      device_class: presence

    ################################################
    ## Climate
    ################################################

    climate.dining_room:
      <<: *customize
      friendly_name: 'Nest'
      icon: mdi:thermostat

    ################################################
    ## Script
    ################################################

    script.set_nest_away:
      <<: *customize
      friendly_name: Set Nest Thermostat Away

    script.set_nest_home:
      <<: *customize
      friendly_name: Set Nest Thermostat Home

    ################################################
    ## Sensor
    ################################################

    sensor.dining_room_thermostat_humidity:
      <<: *customize
      friendly_name: Nest Humidity
      device_class: humidity

    sensor.dining_room_thermostat_hvac_state:
      <<: *customize
      friendly_name: Nest Status
      icon: mdi:thermostat

    sensor.dining_room_thermostat_target:
      <<: *customize
      friendly_name: Nest Target Temperature
      icon: mdi:thermometer-lines

    sensor.dining_room_thermostat_temperature:
      <<: *customize
      friendly_name: Nest Temperature
      device_class: temperature

################################################
## Script
################################################

script:
  set_nest_away:
    sequence:
      - service: nest.set_away_mode
        data:
          away_mode: away

  set_nest_home:
    sequence:
      - service: nest.set_away_mode
        data:
          away_mode: home
