################################################################
## Packages / Presence
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'presence'

      expose: &expose
        <<: *customize
        homebridge_hidden: true

    ################################################
    ## Automation
    ################################################

    automation.life360_overdue_update:
      <<: *expose
      friendly_name: "Life360 Overdue Update"
      icon: mdi:bell-outline

    automation.life360_update_restored:
      <<: *expose
      friendly_name: "Life360 Update Restored"
      icon: mdi:bell-outline

    automation.person_arriving:
      <<: *expose
      friendly_name: "Mark person as just arrived"
      icon: mdi:map-marker

    automation.person_home:
      <<: *expose
      friendly_name: "Mark person as home"
      icon: mdi:map-marker

    automation.person_departing:
      <<: *expose
      friendly_name: "Mark person as just left"
      icon: mdi:map-marker

    automation.person_away:
      <<: *expose
      friendly_name: "Mark person as away"
      icon: mdi:map-marker

    automation.person_vacation:
      <<: *expose
      friendly_name: "Mark person as extended away"
      icon: mdi:map-marker

    ################################################
    ## Person
    ################################################

    person.julia:
      <<: *customize
      entity_picture: /local/img/julia.jpg
      status_select: input_select.julias_status

    person.michael:
      <<: *customize
      entity_picture: /local/img/michael.jpg
      status_select: input_select.michaels_status

    ################################################
    ## Input Select
    ################################################

    input_select.julias_status:
      <<: *customize
      friendly_name: "Julia"
      entity_picture: /local/img/julia.jpg

    input_select.michaels_status:
      <<: *customize
      friendly_name: "Michael"
      entity_picture: /local/img/michael.jpg

    ################################################
    ## Sensor
    ################################################

    sensor.household:
      <<: *customize
      friendly_name: "Household"

################################################
## Device Tracker
################################################

life360:
  accounts:
    - username: !secret life360_username
      password: !secret life360_password
  interval_seconds: 60
  max_update_wait:
    minutes: 90

################################################
## Input Select
################################################

input_select:
  julias_status:
    options:
      - Home
      - Arriving
      - Departing
      - Away
      - Vacation

  michaels_status:
    options:
      - Home
      - Arriving
      - Departing
      - Away
      - Vacation

################################################
## Sensor
################################################

sensor:
  - platform: template
    sensors:
      household:
        value_template: >-
          {% if is_state('input_select.julias_status', 'Home') or is_state('input_select.michaels_status', 'Home') %}
            Home
          {% elif is_state('input_select.julias_status', 'Arriving') or is_state('input_select.michaels_status', 'Arriving') %}
            Arriving
          {% elif is_state('input_select.julias_status', 'Departing') or is_state('input_select.michaels_status', 'Departing') %}
            Departing
          {% elif is_state('input_select.julias_status', 'Vacation') and is_state('input_select.michaels_status', 'Vacation') %}
            Vacation
          {% else %}
            Away
          {% endif %}
        icon_template: >-
          {% set household_status = states('sensor.household') %}
          {% if household_status == 'Home' or household_status == 'Arriving' %}
            mdi:map-marker-radius
          {% elif household_status == 'Vacation' %}
            mdi:beach
          {% else %}
            mdi:car
          {% endif %}

################################################
## Automation
################################################

automation:
  - alias: life360_overdue_update
    initial_state: true
    trigger:
      platform: event
      event_type: life360_update_overdue
    action:
      service: persistent_notification.create
      data_template:
        title: Life360 update overdue
        message: >
          Update for {{
            state_attr(trigger.event.data.entity_id, 'friendly_name') or
            trigger.event.data.entity_id
          }} is overdue.

  - alias: life360_update_restored
    initial_state: true
    trigger:
      platform: event
      event_type: life360_update_restored
    action:
      service: persistent_notification.create
      data_template:
        title: Life360 update restored
        message: >
          Update for {{
            state_attr(trigger.event.data.entity_id, 'friendly_name') or
            trigger.event.data.entity_id
          }} restored after {{ trigger.event.data.wait }}.

  - alias: person_arriving
    initial_state: true
    trigger:
      - platform: state
        entity_id: person.julia
#        from: 'not_home'
        to: 'home'
      - platform: state
        entity_id: person.michael
#        from: 'not_home'
        to: 'home'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: "{{ state_attr(trigger.entity_id, 'status_select') }}"
          option: >-
            {% if is_state(state_attr(trigger.entity_id, 'status_select'), 'Departing') %}
              Home
            {% else %}
              Arriving
            {% endif %}
 
  - alias: person_home
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.julias_status
        to: 'Arriving'
        for:
          minutes: 10
      - platform: state
        entity_id: input_select.michaels_status
        to: 'Arriving'
        for:
          minutes: 10
    action:
      - service: input_select.select_option
        data_template:
          entity_id: '{{ trigger.entity_id }}'
          option: 'Home'
 
  - alias: person_departing
    initial_state: true
    trigger:
      - platform: state
        entity_id: person.julia
        from: 'home'
#        to: 'not_home'
      - platform: state
        entity_id: person.michael
        from: 'home'
#        to: 'not_home'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: "{{ state_attr(trigger.entity_id, 'status_select') }}"
          option: 'Departing'
 
  - alias: person_away
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.julias_status
        to: 'Departing'
        for:
          minutes: 10
      - platform: state
        entity_id: input_select.michaels_status
        to: 'Departing'
        for:
          minutes: 10
    action:
      - service: input_select.select_option
        data_template:
          entity_id: '{{ trigger.entity_id }}'
          option: 'Away'
 
  - alias: person_vacation
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.julias_status
        to: 'Away'
        for:
          hours: 24
      - platform: state
        entity_id: input_select.michaels_status
        to: 'Away'
        for:
          hours: 24
    action:
      - service: input_select.select_option
        data_template:
          entity_id: '{{ trigger.entity_id }}'
          option: 'Vacation'
