################################################################
## Packages / Recorder
## https://home-assistant.io/components/recorder/
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'recorder'

################################################
## Recorder
################################################

recorder:
  auto_purge: true
  purge_keep_days: 10
  exclude:
      domains:
        - camera
        - media_player
        - sun
        - notify
      entities:
        - automation.guest_bedroom_closet_lighting
        - automation.guest_bedroom_storage_lighting
        - automation.michaels_closet_lighting
        - automation.julias_closet_lighting
        - automation.keyfob_circle_button_tapped
        - automation.keyfob_square_button_tapped
        - automation.keyfob_triangle_button_tapped
        - automation.keyfob_x_button_tapped
        - automation.keyfob_minus_button_tapped
        - automation.keyfob_minus_button_held
        - automation.keyfob_plus_button_tapped
        - automation.person_arriving
        - automation.person_home
        - automation.person_departing
        - automation.person_away
        - automation.person_vacation
        - sensor.since_last_boot
        - sensor.since_last_boot_templated
        - sensor.date
        - sensor.time
