################################################################
## Packages / River
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'river'

    ################################################
    ## Sensor
    ################################################

    sensor.river_level:
      <<: *customize
      friendly_name: "River Level"
      icon: mdi:waves

################################################
## Sensor
################################################

sensor:
  - platform: rest
    resource: !secret water_endpoint
    scan_interval: 1800
    method: GET
    name: river_level
    verify_ssl: true
    json_attributes_path: "$.status.observed"
    json_attributes:
      - secondary
      - secondaryUnit
      - floodCategory
      - validTime
    value_template: '{{ value_json["status"]["observed"]["primary"] }}'
    unit_of_measurement: ft
    force_update: true
