################################################################
## Package / Sensor Lights
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'sensor_lights'

    ################################################
    ## Automation
    ################################################

    automation.living_room_motion:
      <<: *customize
      friendly_name: "Living Room Motion"
      icon: mdi:robot

    automation.master_bedroom_motion:
      <<: *customize
      friendly_name: "Bedroom Motion"
      icon: mdi:robot

    automation.guest_bedroom_closet_lighting:
      <<: *customize
      friendly_name: "Guest Closet Lighting"
      icon: mdi:robot

    automation.guest_bedroom_storage_lighting:
      <<: *customize
      friendly_name: "Guest Storage Lighting"
      icon: mdi:robot

    automation.michaels_closet_lighting:
      <<: *customize
      friendly_name: "Michael's Closet Lighting"
      icon: mdi:robot
  
    automation.julias_closet_lighting:
      <<: *customize
      friendly_name: "Julia's Closet Lighting"
      icon: mdi:robot

    automation.nightstand_switches:
      <<: *customize
      friendly_name: "Nightstand Switches"
      icon: mdi:robot

    automation.exterior_lighting:
      <<: *customize
      friendly_name: "Exterior Lighting"
      icon: mdi:robot

################################################
## Automation
################################################

automation:
  ################################################
  ## Motion Activated Lights
  ################################################

  - alias: living_room_motion
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor_home_security_motion_detection
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor_home_security_motion_detection
        from: 'on'
        to: 'off'
        for: '00:25:00'
    mode: restart
    max_exceeded: silent
    action:
      - choose:
          # IF door opened
          - conditions: "{{ trigger.to_state.state == 'on' }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.living_room_floor_lamp_instance_1_level
                data:
                  brightness_pct: 70
                  transition: 2
              - service: light.turn_on
                target:
                  entity_id: light.table_light
                data:
                  brightness_pct: 70
                  transition: 2
                  color_name: "{{ ['coral', 'crimson', 'darkmagenta', 'fuchsia', 'goldenrod', 'honeydew', 'indianred', 'maroon', 'mediumvioletred', 'orange', 'orchid', 'peru', 'red', 'sienna', 'tomato'] | random }}"
        # ELSE door closed
        default:
          - service: light.turn_off
            target:
              entity_id: light.living_room_floor_lamp_instance_1_level, light.table_light
            data:
              transition: 3

  - alias: master_bedroom_motion
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion_sensor_home_security_motion_detection
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion_sensor_home_security_motion_detection
        from: 'on'
        to: 'off'
        for: '00:20:00'
    mode: restart
    max_exceeded: silent
    action:
      - choose:
          # IF door opened
          - conditions: "{{ trigger.to_state.state == 'on' }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.dresser_lamp, light.nightstand_lamp
                data:
                  brightness_pct: 70
                  color_temp: 370
                  transition: 2
        # ELSE door closed
        default:
          - service: light.turn_off
            target:
              entity_id: light.dresser_lamp, light.nightstand_lamp
            data:
              transition: 3

  ################################################
  ## Door Activated Lights
  ################################################

  - alias: guest_bedroom_closet_lighting
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.guest_closet_door_access_control_window_door_is_open
    action:
      - choose:
          # IF door opened
          - conditions: "{{ trigger.to_state.state == 'on' }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.guest_closet_dimmable_led_light_bulb
                data:
                  brightness: 255
                  color_temp: 370
                  transition: 1
        # ELSE door closed
        default:
          - service: light.turn_off
            target:
              entity_id: light.guest_closet_dimmable_led_light_bulb
            data:
              transition: 1

  - alias: guest_bedroom_storage_lighting
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.guest_storage_door_access_control_window_door_is_open
    action:
      - choose:
          # IF door opened
          - conditions: "{{ trigger.to_state.state == 'on' }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.guest_bedroom_storage
                data:
                  brightness: 255
                  color_temp: 370
                  transition: 1
        # ELSE door closed
        default:
          - service: light.turn_off
            target:
              entity_id: light.guest_bedroom_storage
            data:
              transition: 1

  - alias: michaels_closet_lighting
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.michaels_closet_door_access_control_window_door_is_open
    action:
      - choose:
          # IF door opened
          - conditions: "{{ trigger.to_state.state == 'on' }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.michaels_closet
                data:
                  brightness: 255
                  color_temp: 370
                  transition: 1
        # ELSE door closed
        default:
          - service: light.turn_off
            target:
              entity_id: light.michaels_closet
            data:
              transition: 1

  - alias: julias_closet_lighting
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.julias_closet_door_access_control_window_door_is_open
    action:
      - choose:
          # IF door opened
          - conditions: "{{ trigger.to_state.state == 'on' }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.julias_closet
                data:
                  brightness: 255
                  color_temp: 370
                  transition: 1
        # ELSE door closed
        default:
          - service: light.turn_off
            target:
              entity_id: light.julias_closet
            data:
              transition: 1

  ################################################
  ## Sun Activated Lights
  ################################################

  - alias: exterior_lighting
    initial_state: true
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: -4.0
        id: 'on'
      - platform: time
        id: 'off'
        at: '23:59:59'
    condition: []
    action:
      - service: light.turn_{{ trigger.id }}
        target:
          entity_id: light.front_porch_light
      - service: switch.turn_{{ trigger.id }}
        target:
          entity_id: switch.front_porch_outdoor_double_plug, switch.christmas_tree_switch
      - delay: 2
      - service: switch.turn_{{ trigger.id }}
        target:
          entity_id: switch.front_porch_outdoor_double_plug_2
    mode: single
