################################################################
## Package / Sensor Lights
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'sensor_lights'

    ################################################
    ## Automation
    ################################################

    automation.master_bedroom_motion:
      <<: *customize
      friendly_name: "Bedroom Motion"
      icon: mdi:robot


################################################
## Automation
################################################

automation sensorlights:
  ################################################
  ## Motion Activated Lights
  ################################################

  - alias: master_bedroom_motion
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_dresser_motion_sensor_motion_detection
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.master_bedroom_dresser_motion_sensor_motion_detection
        from: 'on'
        to: 'off'
        for: '00:20:00'
    mode: restart
    max_exceeded: silent
    action:
      - choose:
          # IF door opened
          - conditions: "{{ trigger.to_state.state == 'on' }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.nightstand_lamp
                data:
                  brightness_pct: 70
                  color_temp: 370
                  transition: 2
        # ELSE door closed
        default:
          - service: light.turn_off
            target:
              entity_id: light.nightstand_lamp
            data:
              transition: 3
