################################################################
## Package / Sensor Lights
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'sensor_lights'

    ################################################
    ## Automation
    ################################################

    automation.living_room_motion:
      <<: *customize
      friendly_name: "Living Room Motion"
      persistent: true
      icon: mdi:robot

    automation.master_bedroom_motion:
      <<: *customize
      friendly_name: "Bedroom Motion"
      persistent: true
      icon: mdi:robot

    automation.guest_bedroom_closet_lighting:
      <<: *customize
      friendly_name: "Guest Closet Lighting"
      persistent: true
      icon: mdi:robot

    automation.guest_bedroom_storage_lighting:
      <<: *customize
      friendly_name: "Guest Storage Lighting"
      persistent: true
      icon: mdi:robot

    automation.michaels_closet_lighting:
      <<: *customize
      friendly_name: "Michael's Closet Lighting"
      persistent: true
      icon: mdi:robot
  
    automation.julias_closet_lighting:
      <<: *customize
      friendly_name: "Julia's Closet Lighting"
      persistent: true
      icon: mdi:robot

################################################
## Automation
################################################

automation:
  ################################################
  ## Motion Activated Lights
  ################################################

  - alias: living_room_motion
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor_home_security_motion_detected
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor_home_security_motion_detected
        from: 'on'
        to: 'off'
        for: '00:25:00'
    mode: restart
    action:
      - service: script.light_control
        data_template:
          entity_id: light.living_room_floor_lamp_instance_1_level
          state: "{{ trigger.to_state.state }}"
          brightness: 178
          transition: 2
      - service: script.light_control
        data_template:
          entity_id: light.table_light
          state: "{{ trigger.to_state.state }}"
          brightness: 178
          effect: "colorloop"

  - alias: master_bedroom_motion
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion_sensor_home_security_motion_detected
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion_sensor_home_security_motion_detected
        from: 'on'
        to: 'off'
        for: '00:20:00'
    mode: restart
    action:
      - service: script.light_control
        data_template:
          entity_id: light.dresser_lamp
          state: "{{ trigger.to_state.state }}"
          brightness: 178
          transition: 2
      - service: script.light_control
        data_template:
          entity_id: light.nightstand_lamp
          state: "{{ trigger.to_state.state }}"
          brightness: 178
          transition: 2

  ################################################
  ## Door Activated Lights
  ################################################

  - alias: guest_bedroom_closet_lighting
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.guest_closet_door_access_control_door_window_open
    action:
      - service: script.light_control
        data_template:
          entity_id: light.guest_closet_dimmable_led_light_bulb
          state: "{{ trigger.to_state.state }}"
          brightness: 255
          transition: 1

  - alias: guest_bedroom_storage_lighting
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.guest_storage_door_access_control_door_window_open
    action:
      - service: script.light_control
        data_template:
          entity_id: light.guest_bedroom_storage
          state: "{{ trigger.to_state.state }}"
          brightness: 255
          transition: 1

  - alias: michaels_closet_lighting
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.michaels_closet_door_access_control_window_door_is_open
    action:
      - service: script.light_control
        data_template:
          entity_id: light.michaels_closet
          state: "{{ trigger.to_state.state }}"
          brightness: 255
          transition: 1

  - alias: julias_closet_lighting
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.julias_closet_door_access_control_window_door_is_open
    action:
      - service: script.light_control
        data_template:
          entity_id: light.julias_closet
          state: "{{ trigger.to_state.state }}"
          brightness: 255
          transition: 1
