################################################################
## Package / Sensor Lights
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'sensor_lights'

    ################################################
    ## Automation
    ################################################

    automation.living_room_motion:
      <<: *customize
      friendly_name: "Living Room Motion"
      persistent: true
      icon: mdi:robot

    automation.master_bedroom_motion:
      <<: *customize
      friendly_name: "Bedroom Motion"
      persistent: true
      icon: mdi:robot

    automation.guest_bedroom_closet_lighting:
      <<: *customize
      friendly_name: "Guest Closet Lighting"
      persistent: true
      icon: mdi:robot

    automation.guest_bedroom_storage_lighting:
      <<: *customize
      friendly_name: "Guest Storage Lighting"
      persistent: true
      icon: mdi:robot

    automation.michaels_closet_lighting:
      <<: *customize
      friendly_name: "Michael's Closet Lighting"
      persistent: true
      icon: mdi:robot
  
    automation.julias_closet_lighting:
      <<: *customize
      friendly_name: "Julia's Closet Lighting"
      persistent: true
      icon: mdi:robot

    automation.nightstand_switches:
      <<: *customize
      friendly_name: "Nightstand Switches"
      persistent: true
      icon: mdi:robot

################################################
## Automation
################################################

automation:
  ################################################
  ## Motion Activated Lights
  ################################################

  - alias: living_room_motion
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor_home_security_motion_detection
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor_home_security_motion_detection
        from: 'on'
        to: 'off'
        for: '00:25:00'
    mode: restart
    max_exceeded: silent
    action:
      # - service: script.light_control
      #   data_template:
      #     entity_id: light.living_room_floor_lamp_instance_1_level
      #     state: "{{ trigger.to_state.state }}"
      #     brightness: 178
      #     transition: 2
      # - service: script.light_control
      #   data_template:
      #     entity_id: light.table_light
      #     state: "{{ trigger.to_state.state }}"
      #     brightness: 178
      #     effect: "colorloop"
      - service: >
          {% if trigger.to_state.state == "on" %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        target:
          entity_id: light.living_room_floor_lamp_instance_1_level, light.table_light
        data:
          brightness_pct: 70
          color_temp: 370
          transition: 2


  - alias: master_bedroom_motion
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion_sensor_home_security_motion_detection
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion_sensor_home_security_motion_detection
        from: 'on'
        to: 'off'
        for: '00:20:00'
    mode: restart
    max_exceeded: silent
    action:
      # - service: script.light_control
      #   data_template:
      #     entity_id: light.dresser_lamp
      #     state: "{{ trigger.to_state.state }}"
      #     brightness: 178
      #     transition: 2
      # - service: script.light_control
      #   data_template:
      #     entity_id: light.nightstand_lamp
      #     state: "{{ trigger.to_state.state }}"
      #     brightness: 178
      #     transition: 2
      - service: >
          {% if trigger.to_state.state == "on" %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        target:
          entity_id: light.dresser_lamp, light.nightstand_lamp
        data:
          brightness_pct: 70
          color_temp: 370
          transition: 2

  ################################################
  ## Door Activated Lights
  ################################################

  - alias: guest_bedroom_closet_lighting
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.guest_closet_door_access_control_window_door_is_open
    action:
      - service: >
          {% if trigger.to_state.state == "on" %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        target:
          entity_id: light.guest_closet_dimmable_led_light_bulb
        data:
          brightness: 255
          color_temp: 370
          transition: 1

  - alias: guest_bedroom_storage_lighting
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.guest_storage_door_access_control_window_door_is_open
    action:
      - service: >
          {% if trigger.to_state.state == "on" %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        target:
          entity_id: light.guest_bedroom_storage
        data:
          brightness: 255
          color_temp: 370
          transition: 1

  - alias: michaels_closet_lighting
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.michaels_closet_door_access_control_window_door_is_open
    action:
      - choose:
          # IF door opened
          - conditions: "{{ trigger.to_state.state == 'on' }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.michaels_closet
                data:
                  brightness: 255
                  color_temp: 370
                  transition: 1
        # ELSE door closed
        default:
          - service: light.turn_off
            target:
              entity_id: light.michaels_closet

  - alias: julias_closet_lighting
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.julias_closet_door_access_control_window_door_is_open
    action:
      - service: >
          {% if trigger.to_state.state == "on" %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        target:
          entity_id: light.julias_closet
        data:
          brightness: 255
          color_temp: 370
          transition: 1

  ################################################
  ## Switch Activated Lights
  ################################################

  - alias: nightstand_switches
    initial_state: true
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 30
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 31
    action:
      - choose:
        # If Top button 1x
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == 'Scene 001' and trigger.event.data.value == 'KeyPressed' }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.dresser_lamp, light.nightstand_lamp
              data:
                brightness_pct: 100
                color_temp: 370
                transition: 2
        # If Top button 2x
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == 'Scene 001' and trigger.event.data.value == 'KeyPressed2x' }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.dresser_lamp, light.nightstand_lamp
              data:
                brightness_pct: 70
                color_temp: 370
                transition: 2
        # If Top button 3x
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == 'Scene 001' and trigger.event.data.value == 'KeyPressed3x' }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.dresser_lamp, light.nightstand_lamp
              data:
                brightness_pct: 50
                color_temp: 370
                transition: 2
        # If Top button 4x
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == 'Scene 001' and trigger.event.data.value == 'KeyPressed4x' }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.dresser_lamp, light.nightstand_lamp
              data:
                brightness_pct: 30
                color_temp: 370
                transition: 2
        # If Top button 5x
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == 'Scene 001' and trigger.event.data.value == 'KeyPressed5x' }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.dresser_lamp, light.nightstand_lamp
              data:
                brightness_pct: 10
                color_temp: 370
                transition: 2
        # If Bottom button 1x
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == 'Scene 002' and trigger.event.data.value == 'KeyPressed' }}"
          sequence:
            - service: light.turn_off
              target:
                entity_id: light.dresser_lamp, light.nightstand_lamp
              data:
                transition: 3
