################################################################
## Packages / Sonos
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'sonos'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Media Player
    ################################################

    media_player.dining_room:
      <<: *expose
      friendly_name: 'Dining Room Sonos'
      icon: mdi:speaker

    media_player.living_room:
      <<: *expose
      friendly_name: 'Living Room Sonos'
      icon: mdi:speaker

    media_player.office:
      <<: *expose
      friendly_name: 'Office Sonos'
      icon: mdi:speaker

################################################
## Script
################################################

script:
  sonos_say:
    alias: "Sonos TTS script"
    sequence:
     - service: sonos.snapshot
       data_template:
         entity_id: "{{ sonos_entity|default('media_player.living_room') }}"
     - service: sonos.unjoin
       data_template:
         entity_id: "{{ sonos_entity|default('media_player.living_room') }}"
     - service: media_player.volume_set
       data_template:
         entity_id: "{{ sonos_entity|default('media_player.living_room') }}"
         volume_level: "{{ volume }}"
     - service: tts.google_translate_say
       data_template:
         entity_id: "{{ sonos_entity|default('media_player.living_room') }}"
         message: "{{ message }}"
     - delay: "{{ delay }}"
     - wait_template: "{{ is_state(sonos_entity|default('media_player.living_room'), 'playing') }}"
       timeout: '00:00:05'
     - wait_template: "{{ not is_state(sonos_entity|default('media_player.living_room'), 'playing') }}"
       timeout: '00:02:00'
     - service: sonos.restore
       data_template:
         entity_id: "{{ sonos_entity|default('media_player.living_room') }}"
