################################################################
## Packages / Synology
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'synology'

################################################
## DSM
################################################

# https://www.home-assistant.io/integrations/synology_dsm/
synology_dsm:
  - host: !secret nas_host
    ssl: true
    verify_ssl: true
    username: !secret nas_username
    password: !secret nas_password
