################################################################
## Packages / System
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'system'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.startup_notification:
      <<: *customize
      friendly_name: "Startup Notification"
      icon: mdi:message-text

    automation.update_notification:
      <<: *customize
      friendly_name: "Update Notification"
      icon: mdi:message-text

    ################################################
    ## Sensor
    ################################################

    sensor.date:
      <<: *customize
      friendly_name: "System Date"
      icon: mdi:calendar

    sensor.speedtest_ping:
      <<: *customize
      friendly_name: Ping
      icon: mdi:pulse

    sensor.speedtest_download:
      <<: *customize
      friendly_name: Download
      icon: mdi:download

    sensor.speedtest_upload:
      <<: *customize
      friendly_name: Upload
      icon: mdi:upload

    sensor.time:
      <<: *customize
      friendly_name: "System Time"
      icon: mdi:clock

################################################
## Automation
################################################

automation system:
  - alias: startup_notification
    initial_state: true
    trigger:
      - platform: homeassistant
        event: start
#      - platform: time_pattern
#        seconds: '/5'
    action:
      - service: frontend.set_theme
        data:
          name: LCARS Modern
          # name: default
          mode: dark
      - service: notify.sms
        data:
          message: "Home Assistant is now up and running."
          target:
            - !secret mobile_michael
      - service: automation.turn_off
        data:
          entity_id: automation.startup_notification

  - alias: update_notification
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.updater
        from: 'off'
        to: 'on'
    action:
      - service: notify.sms
        data_template:
          message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available."
          target:
            - !secret mobile_michael

################################################
## Sensor
################################################

sensor:
  # https://www.home-assistant.io/components/sensor.time_date/
  - platform: time_date
    display_options:
      - date
      - time
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
