################################################################
## Packages / Weather
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'weather'

    ################################################
    ## Sensor
    ################################################

    sensor.dark_sky_cloud_coverage:
      <<: *customize
      friendly_name: "Cloud Coverage"
      icon: mdi:weather-partlycloudy

    sensor.dark_sky_humidity:
      <<: *customize
      friendly_name: "Humidity"
      device_class: humidity

    sensor.dark_sky_precip_probability:
      <<: *customize
      friendly_name: "Chance Precipitation"
      icon: mdi:weather-rainy

    sensor.dark_sky_precip:
      <<: *customize
      friendly_name: 'Precipitation'
      icon: mdi:weather-pouring

    sensor.dark_sky_temperature:
      <<: *customize
      friendly_name: "Temperature"
      icon: mdi:thermometer

    sensor.dark_sky_wind_speed:
      <<: *customize
      friendly_name: 'Wind Speed'
      icon: mdi:weather-windy

    sensor.river_level:
      <<: *customize
      friendly_name: "River Level"
      icon: mdi:waves

    sensor.season:
      <<: *customize
      friendly_name: "Season"
      icon: mdi:weather-snowy-rainy

################################################
## Sensor
################################################

sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - cloud_cover
      - humidity
      - precip_probability
      - precip_type
      - temperature
      - wind_speed

  - platform: season
    type: astronomical

  - platform: rest
    resource: !secret water_endpoint
    scan_interval: 90
    json_attributes:
      - "valid"
      - "secondary"
    method: GET
    name: river_level
    verify_ssl: true
    json_attributes_path: "$.site.observed.datum.[:1]"
    value_template: '{{ value_json["site"]["observed"]["datum"][0]["primary"]["#text"] }}'
    unit_of_measurement: ft
    force_update: true

################################################
## Weather
################################################

# Dark Sky
# https://www.home-assistant.io/components/weather.darksky/
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily
