################################################################
## Packages / WirelessTag
## https://www.home-assistant.io/components/wirelesstag/
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'wirelesstag'

    ################################################
    ## Plant
    ################################################

    plant.workroom_closet:
      <<: *customize
      friendly_name: 'Workroom Closet'

    plant.humidor:
      <<: *customize
      friendly_name: 'Humidor'

    plant.wine_rack:
      <<: *customize
      friendly_name: 'Wine Rack'

    ################################################
    ## Sensor
    ################################################
    sensor.wirelesstag_workroom_closet_battery_level:
      <<: *customize
      friendly_name: 'Workroom Closet: Battery Level'
      device_class: battery

    sensor.wirelesstag_workroom_closet_humidity:
      <<: *customize
      friendly_name: 'Workroom Closet: Humidity'
      device_class: humidity

    sensor.wirelesstag_workroom_closet_light:
      <<: *customize
      friendly_name: 'Workroom Closet: Illuminance'
      device_class: illuminance

    sensor.wirelesstag_workroom_closet_temperature:
      <<: *customize
      friendly_name: 'Workroom Closet: Temperature'
      device_class: temperature

    sensor.wirelesstag_humidor_battery_level:
      <<: *customize
      friendly_name: 'Humidor: Battery Level'
      device_class: battery

    sensor.wirelesstag_humidor_humidity:
      <<: *customize
      friendly_name: 'Humidor: Humidity'
      device_class: humidity

    sensor.wirelesstag_humidor_light:
      <<: *customize
      friendly_name: 'Humidor: Illuminance'
      device_class: illuminance

    sensor.wirelesstag_humidor_temperature:
      <<: *customize
      friendly_name: 'Humidor: Temperature'
      device_class: temperature

    sensor.wirelesstag_wine_rack_battery_level:
      <<: *customize
      friendly_name: 'Wine Rack: Battery Level'
      device_class: battery

    sensor.wirelesstag_wine_rack_humidity:
      <<: *customize
      friendly_name: 'Wine Rack: Humidity'
      device_class: humidity

    sensor.wirelesstag_wine_rack_light:
      <<: *customize
      friendly_name: 'Wine Rack: Illuminance'
      device_class: illuminance

    sensor.wirelesstag_wine_rack_temperature:
      <<: *customize
      friendly_name: 'Wine Rack: Temperature'
      device_class: temperature

################################################
## Sensors
## https://www.home-assistant.io/components/sensor.wirelesstag/
################################################

sensor:
  - platform: wirelesstag
    monitored_conditions:
      - temperature
      - humidity
      - light

  - platform: template
    sensors:
      wirelesstag_workroom_closet_battery_level:
        value_template: '{{ (states.sensor.wirelesstag_workroom_closet_humidity.attributes.battery_level|float)|round }}'
        unit_of_measurement: '%'

      wirelesstag_humidor_battery_level:
        value_template: '{{ (states.sensor.wirelesstag_humidor_humidity.attributes.battery_level|float)|round }}'
        unit_of_measurement: '%'

      wirelesstag_wine_rack_battery_level:
        value_template: '{{ (states.sensor.wirelesstag_wine_rack_humidity.attributes.battery_level|float)|round }}'
        unit_of_measurement: '%'

################################################
## Plants
## https://www.home-assistant.io/components/plant/
################################################

plant:
  workroom_closet:
    sensors:
      moisture: sensor.wirelesstag_workroom_closet_humidity
      battery: sensor.wirelesstag_workroom_closet_battery_level
      temperature: sensor.wirelesstag_workroom_closet_temperature
      brightness: sensor.wirelesstag_workroom_closet_light
    min_moisture: 25
    max_moisture: 50
    min_battery: 10
    min_temperature: 55
    max_temperature: 80

  humidor:
    sensors:
      moisture: sensor.wirelesstag_humidor_humidity
      battery: sensor.wirelesstag_humidor_battery_level
      temperature: sensor.wirelesstag_humidor_temperature
      brightness: sensor.wirelesstag_humidor_light
    min_moisture: 55
    max_moisture: 75
    min_battery: 10
    min_temperature: 60
    max_temperature: 79

  wine_rack:
    sensors:
      moisture: sensor.wirelesstag_wine_rack_humidity
      battery: sensor.wirelesstag_wine_rack_battery_level
      temperature: sensor.wirelesstag_wine_rack_temperature
      brightness: sensor.wirelesstag_wine_rack_light
    min_moisture: 35
    max_moisture: 50
    min_battery: 10
    min_temperature: 50
    max_temperature: 80

################################################
## WirelessTag
################################################

# WirelessTag
wirelesstag:
  username: !secret wirelesstag_username
  password: !secret wirelesstag_password
