################################################################
## Packages / Zabbix
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'zabbix'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

################################################
## Zabbix
################################################

# Zabbix
# https://www.home-assistant.io/integrations/zabbix/
zabbix:
  host: 192.168.1.35
