################################################################
## Packages / Z-Wave
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'zwave'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Binary Sensor
    ################################################

    # binary_sensor.entrance_front_door_contact:
    #   <<: *customize
    #   friendly_name: Entrance Front Door
    #   device_class: door

    # binary_sensor.garage_door_opener:
    #   <<: *customize
    #   friendly_name: Garage Door
    #   device_class: garage_door

    # binary_sensor.guest_bedroom_closet_door_contact:
    #   <<: *customize
    #   friendly_name: Guest Bedroom Closet Door
    #   device_class: door

    # binary_sensor.guest_bedroom_storage_door_contact:
    #   <<: *customize
    #   friendly_name: Guest Bedroom Storage Door
    #   device_class: door

    # binary_sensor.julias_closet_door_contact:
    #   <<: *customize
    #   friendly_name: "Julia's Closet Door"
    #   device_class: door

    binary_sensor.kitchen_motion_sensor:
      <<: *customize
      friendly_name: Kitchen Motion Sensor
      device_class: motion

    # binary_sensor.living_room_motion_sensor:
    #   <<: *customize
    #   friendly_name: Living Room Motion Sensor
    #   device_class: motion

    # binary_sensor.master_bedroom_motion_sensor:
    #   <<: *customize
    #   friendly_name: Master Bedroom Motion Sensor
    #   device_class: motion

    # binary_sensor.michaels_closet_door_contact:
    #   <<: *customize
    #   friendly_name: "Michael's Closet Door"
    #   device_class: door

    ################################################
    ## Cover
    ################################################

    # cover.garage_door_opener:
    #   <<: *customize
    #   friendly_name: Garage Door
    #   device_class: garage

    ################################################
    ## Lights
    ################################################

    light.basement_task_light:
      <<: *customize
      friendly_name: Basement Task Light
      icon: mdi:desk-lamp

    # light.living_room_bookshelf_lamp:
    #   <<: *customize
    #   friendly_name: Bookshelf Lamp
    #   icon: mdi:desk-lamp

    # light.living_room_floor_lamp:
    #   <<: *customize
    #   friendly_name: Floor Lamp
    #   icon: mdi:floor-lamp

    # light.guest_bedroom_closet:
    #   <<: *customize
    #   friendly_name: Guest Closet Light
    #   icon: mdi:lightbulb

    # light.garage_storage:
    #   <<: *customize
    #   friendly_name: Garage Storage Light
    #   icon: mdi:lightbulb

    # light.dungeon:
    #   <<: *customize
    #   friendly_name: Dungeon Light
    #   icon: mdi:lightbulb

    ################################################
    ## Sensor
    ################################################

    sensor.guest_bedroom_smoke_and_carbon_monoxide_detector_battery:
      <<: *customize
      friendly_name: Guest Bedroom Smoke Detector Battery Level
      device_class: battery

    sensor.guest_bedroom_smoke_and_carbon_monoxide_detector_alarm_level:
      <<: *customize
      friendly_name: Guest Bedroom Smoke Detector
      icon: mdi:smoke-detector

    sensor.guest_bedroom_closet_door_contact_battery:
      <<: *customize
      friendly_name: Guest Bedroom Closet Door Battery Level
      device_class: battery

    sensor.guest_bedroom_storage_door_contact_battery:
      <<: *customize
      friendly_name: Guest Bedroom Storage Door Battery Level
      device_class: battery

    sensor.guest_bedroom_storage_door_contact_burglar:
      <<: *customize
      friendly_name: Guest Bedroom Closet Door Contact Burglar
      icon: mdi:alarm-bell

    sensor.julias_closet_door_contact_battery:
      <<: *customize
      friendly_name: "Julia's Closet Door Battery Level"
      device_class: battery

    sensor.julias_closet_door_contact_burglar:
      <<: *customize
      friendly_name: "Julia's Closet Door Contact Burglar"
      icon: mdi:alarm-bell

    sensor.kitchen_motion_sensor_battery:
      <<: *customize
      friendly_name: "Kitchen Motion Sensor Battery Level"
      device_class: battery

    sensor.kitchen_motion_sensor_burglar:
      <<: *customize
      friendly_name: "Kitchen Motion Sensor Burglar"
      icon: mdi:alarm-bell

    sensor.kitchen_motion_sensor_luminance:
      <<: *customize
      friendly_name: Kitchen Motion Sensor Luminance
      device_class: illuminance

    sensor.kitchen_motion_sensor_temperature:
      <<: *customize
      friendly_name: Kitchen Motion Sensor Temperature
      device_class: temperature

    sensor.laundry_room_flood_sensor:
      <<: *customize
      friendly_name: Laundry Room Flood Sensor
      icon: mdi:water

    sensor.laundry_room_flood_sensor_battery:
      <<: *customize
      friendly_name: Laundry Room Flood Sensor Battery Level
      device_class: battery

    sensor.laundry_room_flood_sensor_burglar:
      <<: *customize
      friendly_name: Laundry Room Flood Sensor Burglar
      icon: mdi:alarm-bell

    sensor.laundry_room_flood_sensor_temperature:
      <<: *customize
      friendly_name: Laundry Room Flood Sensor Temperature
      device_class: temperature

    sensor.laundry_room_smoke_and_carbon_monoxide_detector_alarm_level:
      <<: *customize
      friendly_name: Laundry Room Smoke Detector
      icon: mdi:smoke-detector

    sensor.laundry_room_smoke_and_carbon_monoxide_detector_battery:
      <<: *customize
      friendly_name: Laundry Room Smoke Detector Battery Level
      device_class: battery

    # sensor.living_room_motion_sensor_battery:
    #   <<: *customize
    #   friendly_name: Living Room Motion Sensor Battery Level
    #   device_class: battery

    # sensor.living_room_motion_sensor_burglar:
    #   <<: *customize
    #   friendly_name: Living Room Motion Sensor Burglar
    #   icon: mdi:alarm-bell

    # sensor.living_room_motion_sensor_luminance:
    #   <<: *customize
    #   friendly_name: Living Room Motion Sensor Luminance
    #   device_class: illuminance

    # sensor.living_room_motion_sensor_seismic_intensity:
    #   <<: *customize
    #   friendly_name: Living Room Motion Sensor Seismic Intensity
    #   icon: mdi:vibrate

    # sensor.living_room_motion_sensor_temperature:
    #   <<: *customize
    #   friendly_name: Living Room Motion Sensor Temperature
    #   device_class: temperature

    # sensor.master_bedroom_motion_sensor_burglar:
    #   <<: *customize
    #   friendly_name: Master Bedroom Motion Sensor Burglar
    #   icon: mdi:alarm-bell

    # sensor.master_bedroom_motion_sensor_luminance:
    #   <<: *customize
    #   friendly_name: Master Bedroom Motion Sensor Luminance
    #   device_class: illuminance

    # sensor.master_bedroom_motion_sensor_relative_humidity:
    #   <<: *customize
    #   friendly_name: Master Bedroom Motion Sensor Humidity
    #   device_class: humidity

    # sensor.master_bedroom_motion_sensor_temperature:
    #   <<: *customize
    #   friendly_name: Master Bedroom Motion Sensor Temperature
    #   device_class: temperature

    sensor.master_bedroom_smoke_and_carbon_monoxide_detector_alarm_level:
      <<: *customize
      friendly_name: Master Bedroom Smoke Detector
      icon: mdi:smoke-detector

    sensor.master_bedroom_smoke_and_carbon_monoxide_detector_battery:
      <<: *customize
      friendly_name: Master Bedroom Smoke Detector Battery Level
      device_class: battery

    sensor.michaels_closet_door_contact_battery:
      <<: *customize
      friendly_name: "Michael's Closet Door Battery Level"
      device_class: battery

    sensor.michaels_closet_door_contact_burglar:
      <<: *customize
      friendly_name: "Michael's Closet Door Contact Burglar"
      icon: mdi:alarm-bell

    sensor.office_smoke_and_carbon_monoxide_detector_alarm_level:
      <<: *customize
      friendly_name: Office Smoke Detector
      icon: mdi:smoke-detector

    sensor.office_smoke_and_carbon_monoxide_detector_battery:
      <<: *customize
      friendly_name: Office Smoke Detector Battery Level
      device_class: battery

    ################################################
    ## Switches
    ################################################

    switch.basement_task_light:
      <<: *customize
      friendly_name: Basement Task Light
      icon: mdi:desk-lamp

    ################################################
    ## Z-Wave
    ################################################

    # zwave.homeseer_smartstick_plus_g2:
    #   friendly_name: "Z-Wave USB Hub"

    zwave.basement_task_light:
      friendly_name: "Basement Task Light"

    # zwave.dungeon_light_bulb:
    #   friendly_name: "Dungeon Light Bulb"

    # zwave.entrance_front_door_contact:
    #   friendly_name: "Entrance Front Door Contact"

    # zwave.garage_door_opener:
    #   friendly_name: "Garage Door Opener"

    # zwave.garage_storage_light_bulb:
    #   friendly_name: "Garage Storage Light Bulb"

    # zwave.guest_bedroom_closet_door_contact:
    #   friendly_name: "Guest Bedroom Closet Door Contact"

    # zwave.guest_bedroom_closet_light_bulb:
    #   friendly_name: "Guest Bedroom Closet Light Bulb"

    zwave.guest_bedroom_smoke_and_carbon_monoxide_detector:
      friendly_name: "Guest Bedroom Smoke and Carbon Monoxide Detector"

    # zwave.guest_bedroom_storage_door_contact:
    #   friendly_name: "Guest Bedroom Storage Door Contact"

    # zwave.julias_closet_door_contact:
    #   friendly_name: "Julia's Closet Door Contact"

    zwave.kitchen_motion_sensor:
      friendly_name: "Kitchen Motion Sensor"

    zwave.kitchen_range_extender:
      friendly_name: "Kitchen Range Extender"

    zwave.laundry_room_flood_sensor:
      friendly_name: "Laundry Room Flood Sensor"

    zwave.laundry_room_range_extender:
      friendly_name: "Laundry Room Range Extender"

    zwave.laundry_room_smoke_and_carbon_monoxide_detector:
      friendly_name: "Laundry Room Smoke and Carbon Monoxide Detector"

    # zwave.living_room_bookshelf_lamp:
    #   friendly_name: "Living Room Bookshelf Lamp"

    # zwave.living_room_floor_lamp:
    #   friendly_name: "Living Room Floor Lamp"

    # zwave.living_room_motion_sensor:
    #   friendly_name: "Living Room Motion Sensor"

    # zwave.master_bedroom_motion_sensor:
    #   friendly_name: "Master Bedroom Motion Sensor"

    zwave.master_bedroom_smoke_and_carbon_monoxide_detector:
      friendly_name: "Master Bedroom Smoke and Carbon Monoxide Detector"

    zwave.master_bedroom_remote:
      friendly_name: "Master Bedroom Remote"

    # zwave.michaels_closet_door_contact:
    #   friendly_name: "Michael's Closet Door Contact"

    zwave.office_smoke_and_carbon_monoxide_detector:
      friendly_name: "Office Smoke and Carbon Monoxide Detector"

  ################################################
  ## Customize Domain
  ################################################

  # customize_domain:
  #   zwave:
  #     <<: *customize
      # hidden: true

################################################
## Light
################################################

light:
  - platform: switch
    name: Basement Task Light
    entity_id: switch.basement_task_light

################################################
## Sensors
################################################

sensor:
  - platform: template
    sensors:
      guest_bedroom_closet_door_contact_battery:
        entity_id: zwave.guest_bedroom_closet_door_contact
        value_template: "{{ (states.zwave.guest_bedroom_closet_door_contact.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'

      guest_bedroom_storage_door_contact_battery:
        entity_id: zwave.guest_bedroom_storage_door_contact
        value_template: "{{ (states.zwave.guest_bedroom_storage_door_contact.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'

      guest_bedroom_smoke_and_carbon_monoxide_detector_battery:
        entity_id: zwave.guest_bedroom_smoke_and_carbon_monoxide_detector
        value_template: "{{ (states.zwave.guest_bedroom_smoke_and_carbon_monoxide_detector.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'

      julias_closet_door_contact_battery:
        entity_id: zwave.julias_closet_door_contact
        value_template: "{{ (states.zwave.julias_closet_door_contact.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'

      kitchen_motion_sensor_battery:
        entity_id: zwave.kitchen_motion_sensor
        value_template: "{{ (states.zwave.kitchen_motion_sensor.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'

      laundry_room_flood_sensor_battery:
        entity_id: zwave.laundry_room_flood_sensor
        value_template: "{{ (states.zwave.laundry_room_flood_sensor.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'

      laundry_room_smoke_and_carbon_monoxide_detector_battery:
        entity_id: zwave.laundry_room_smoke_and_carbon_monoxide_detector
        value_template: "{{ (states.zwave.laundry_room_smoke_and_carbon_monoxide_detector.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'

      # living_room_motion_sensor_battery:
      #   entity_id: zwave.living_room_motion_sensor
      #   value_template: "{{ (states.zwave.living_room_motion_sensor.attributes|default).battery_level|default|int('unknown') }}"
      #   unit_of_measurement: '%'

      master_bedroom_smoke_and_carbon_monoxide_detector_battery:
        entity_id: zwave.master_bedroom_smoke_and_carbon_monoxide_detector
        value_template: "{{ (states.zwave.master_bedroom_smoke_and_carbon_monoxide_detector.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'

      michaels_closet_door_contact_battery:
        entity_id: zwave.michaels_closet_door_contact
        value_template: "{{ (states.zwave.michaels_closet_door_contact.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'

      office_smoke_and_carbon_monoxide_detector_battery:
        entity_id: zwave.office_smoke_and_carbon_monoxide_detector
        value_template: "{{ (states.zwave.office_smoke_and_carbon_monoxide_detector.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'

################################################
## Z-Wave
################################################

#zwave:
#  usb_path: /dev/ttyACM0
#  network_key: !secret zwave_network_key
#  device_config: !include ../zwave_device_config.yaml
