################################################################
## Packages / Z-Wave Remotes
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'zwave_remotes'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.master_bedroom_keyfob:
      <<: *customize
      friendly_name: "Bedroom Keyfob Control"
      icon: mdi:remote

    automation.nightstand_switches:
      <<: *customize
      friendly_name: "Bedroom Nightstand Switch Light Control"
      icon: mdi:light-switch

################################################
## Automation
################################################

automation:

  ################################################
  ## Remote
  ################################################

  - alias: master_bedroom_keyfob
    initial_state: true
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 18
    action:
      - choose:
        # Circle
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == '002' and trigger.event.data.value == 'KeyPressed' }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.nightstand_lamp
              data:
                brightness_pct: 70
                color_temp: 370
                transition: 2
        # Square
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == '001' and trigger.event.data.value == 'KeyPressed' }}"
          sequence:
            - service: light.turn_off
              target:
                entity_id: light.nightstand_lamp
              data:
                transition: 2

        # Triangle
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == '004' and trigger.event.data.value == 'KeyPressed' }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.dresser_lamp
              data:
                brightness_pct: 70
                color_temp: 370
                transition: 2
        # X
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == '003' and trigger.event.data.value == 'KeyPressed' }}"
          sequence:
            - service: light.turn_off
              target:
                entity_id: light.dresser_lamp
              data:
                transition: 2

        # Minus
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == '005' and trigger.event.data.value == 'KeyPressed' }}"
          sequence:
            - service: automation.turn_off
              data:
                entity_id:
                  - automation.master_bedroom_motion
        # Minus - Held
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == '005' and trigger.event.data.value == 'KeyHeldDown' }}"
          sequence:
            - service: alarm_control_panel.alarm_arm_night
              entity_id: alarm_control_panel.alarm_system
              data:
                code: !secret alarm_code

        # Plus
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == '006' and trigger.event.data.value == 'KeyPressed' }}"
          sequence:
            - service: automation.turn_on
              data:
                entity_id:
                  - automation.master_bedroom_motion

  ################################################
  ## Switches
  ################################################

  - alias: nightstand_switches
    initial_state: true
    mode: restart
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 14
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 15
    action:
      - choose:
        # If Top button 1x
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == 'Scene 001' and trigger.event.data.value == 'KeyPressed' }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.nightstand_lamp
              data:
                brightness_pct: 100
                color_temp: 370
                transition: 2
        # If Top button held
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == 'Scene 001' and trigger.event.data.value == 'KeyHeldDown' }}"
          sequence:
            - repeat:
                while: '{{ repeat.index <= 5 | int and states.light.nightstand_lamp.attributes.brightness|default(0) <  255 }}'
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: light.nightstand_lamp
                    data:
                      #brightness: '{{ states.light.nightstand_lamp.attributes.brightness|default(17)|int + (repeat.index * 17) | int }}'
                      brightness_step_pct: 20
                      color_temp: 370
                      transition: 1
                  - delay: 1
        # If Bottom button 1x
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == 'Scene 002' and trigger.event.data.value == 'KeyPressed' }}"
          sequence:
            - service: light.turn_off
              target:
                entity_id: light.nightstand_lamp
              data:
                transition: 3
        # If Bottom button held
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == 'Scene 002' and trigger.event.data.value == 'KeyHeldDown' }}"
          sequence:
            - repeat:
                while: '{{ repeat.index <= 5 | int and states.light.nightstand_lamp.attributes.brightness|default(0) > 51 }}'
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: light.nightstand_lamp
                    data:
                      #brightness: '{{ states.light.nightstand_lamp.attributes.brightness|default(255)|int - (repeat.index * 17) | int }}'
                      brightness_step_pct: -20
                      color_temp: 370
                      transition: 1
                  - delay: 1
        # If Bottom button 3x
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == 'Scene 002' and trigger.event.data.value == 'KeyPressed3x' }}"
          sequence:
            - service: alarm_control_panel.alarm_arm_night
              entity_id: alarm_control_panel.alarm_system
              data:
                code: !secret alarm_code

  - alias: workroom_switches
    initial_state: true
    mode: restart
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 33
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 34
    action:
      - choose:
        # If Top button 1x
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == 'Scene 001' and trigger.event.data.value == 'KeyPressed' }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.workroom_light
              data:
                brightness_pct: 100
                transition: 2
        # If Top button held
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == 'Scene 001' and trigger.event.data.value == 'KeyHeldDown' }}"
          sequence:
            - repeat:
                while: '{{ repeat.index <= 5 | int and states.light.workroom_light.attributes.brightness|default(0) <  255 }}'
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: light.workroom_light
                    data:
                      #brightness: '{{ states.light.nightstand_lamp.attributes.brightness|default(17)|int + (repeat.index * 17) | int }}'
                      brightness_step_pct: 20
                      transition: 1
                  - delay: 1
        # If Bottom button 1x
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == 'Scene 002' and trigger.event.data.value == 'KeyPressed' }}"
          sequence:
            - service: light.turn_off
              target:
                entity_id: light.workroom_light
              data:
                transition: 3
        # If Bottom button held
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == 'Scene 002' and trigger.event.data.value == 'KeyHeldDown' }}"
          sequence:
            - repeat:
                while: '{{ repeat.index <= 5 | int and states.light.workroom_light.attributes.brightness|default(0) > 51 }}'
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: light.workroom_light
                    data:
                      #brightness: '{{ states.light.nightstand_lamp.attributes.brightness|default(255)|int - (repeat.index * 17) | int }}'
                      brightness_step_pct: -20
                      transition: 1
                  - delay: 1
