################################################################
## Packages / Z-Wave Remotes
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'zwave_remotes'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.keyfob_circle_button_tapped:
      <<: *customize
      friendly_name: "Circle Button Tap Nightstand Light On"
      icon: mdi:circle-outline

    automation.keyfob_square_button_tapped:
      <<: *customize
      friendly_name: "Square Button Tap Nightstand Light Off"
      icon: mdi:square-outline

    automation.keyfob_triangle_button_tapped:
      <<: *customize
      friendly_name: "Tringle Button Tap Dresser Light On"
      icon: mdi:triangle-outline

    automation.keyfob_x_button_tapped:
      <<: *customize
      friendly_name: "X Button Tap Dresser Light Off"
      icon: mdi:window-close

    automation.keyfob_minus_button_tapped:
      <<: *customize
      friendly_name: "Minus Button Tap Bedroom Motion Off"
      icon: mdi:minus

    automation.keyfob_minus_button_held:
      <<: *customize
      friendly_name: "Minus Button Hold Night Mode On"
      icon: mdi:minus

    automation.keyfob_plus_button_tapped:
      <<: *customize
      friendly_name: "Plus Button Tap Bedroom Motion On"
      icon: mdi:plus

################################################
## Automation
################################################

automation:

  ################################################
  ## Circle/Square Button
  ################################################

  - alias: keyfob_circle_button_tapped
    hide_entity: true
    initial_state: true
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_bedroom_remote
          scene_id: 2
          scene_data: 7680
    action:
      - service: script.light_control
        data_template:
          entity_id: light.nightstand_lamp
          state: 'on'
          brightness: 178
          transition: 2

  - alias: keyfob_square_button_tapped
    hide_entity: true
    initial_state: true
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_bedroom_remote
          scene_id: 1
          scene_data: 7680
    action:
      - service: script.light_control
        data_template:
          entity_id: light.nightstand_lamp
          state: 'off'
          brightness: 178
          transition: 2

  ################################################
  ## Triangle/X Button
  ################################################

  - alias: keyfob_triangle_button_tapped
    hide_entity: true
    initial_state: true
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_bedroom_remote
          scene_id: 4
          scene_data: 7680
    action:
      - service: script.light_control
        data_template:
          entity_id: light.dresser_lamp
          state: 'on'
          brightness: 178
          transition: 2

  - alias: keyfob_x_button_tapped
    hide_entity: true
    initial_state: true
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_bedroom_remote
          scene_id: 3
          scene_data: 7680
    action:
      - service: script.light_control
        data_template:
          entity_id: light.dresser_lamp
          state: 'off'
          brightness: 178
          transition: 2

  ################################################
  ## Minus Button
  ################################################

  - alias: keyfob_minus_button_tapped
    hide_entity: true
    initial_state: true
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_bedroom_remote
          scene_id: 5
          scene_data: 7680
    action:
      - service: automation.turn_off
        data:
          entity_id:
            - automation.master_bedroom_motion

  - alias: keyfob_minus_button_held
    hide_entity: true
    initial_state: true
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_bedroom_remote
          scene_id: 5
          scene_data: 7800
    action:
      - service: alarm_control_panel.alarm_arm_night
        entity_id: alarm_control_panel.alarm_system
        data:
          code: !secret alarm_code

  ################################################
  ## Plus Button
  ################################################

  - alias: keyfob_plus_button_tapped
    hide_entity: true
    initial_state: true
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_bedroom_remote
          scene_id: 6
          scene_data: 7680
    action:
      - service: automation.turn_on
        data:
          entity_id:
            - automation.master_bedroom_motion
