################################################################
## Packages / Z-Wave
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'zwave'

      expose: &expose
        <<: *customize
        homebridge_hidden: false
