################################################################
## Packages / Z-Wave
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'zwave'

      expose: &expose
        <<: *customize
        homebridge_hidden: false

    ################################################
    ## Binary Sensor
    ################################################

    binary_sensor.entrance_front_door_sensor:
      <<: *customize
      friendly_name: Entrance Front Door
      device_class: door

    binary_sensor.garage_door_sensor:
      <<: *customize
      friendly_name: Garage Door
      device_class: garage_door

    binary_sensor.guest_closet_door_access_control_door_window_open:
      <<: *customize
      friendly_name: Guest Bedroom Closet Door
      device_class: door

    binary_sensor.guest_storage_door_access_control_door_window_open:
      <<: *customize
      friendly_name: Guest Bedroom Storage Door
      device_class: door

    binary_sensor.julias_closet_door_access_control_door_window_open:
      <<: *customize
      friendly_name: "Julia's Closet Door"
      device_class: door

    binary_sensor.kitchen_motion_sensor_home_security_motion_detected:
      <<: *customize
      friendly_name: Kitchen Motion Sensor
      device_class: motion

    binary_sensor.living_room_motion_sensor_home_security_motion_detected:
      <<: *customize
      friendly_name: Living Room Motion Sensor
      device_class: motion

    binary_sensor.master_bedroom_motion_sensor_home_security_motion_detected:
      <<: *customize
      friendly_name: Master Bedroom Motion Sensor
      device_class: motion

    binary_sensor.michaels_closet_door_access_control_door_window_open:
      <<: *customize
      friendly_name: "Michael's Closet Door"
      device_class: door

    binary_sensor.ozw_network_ready:
      <<: *customize
      friendly_name: "Z-Wave Network Ready"
      device_class: connectivity

    ################################################
    ## Cover
    ################################################

    cover.garage_door_barrier_state:
      <<: *customize
      friendly_name: Garage Door
      device_class: garage

    ################################################
    ## Lights
    ################################################

    light.basement_task_light:
      <<: *customize
      friendly_name: Basement Task Light
      icon: mdi:desk-lamp

    light.living_room_bookshelf_lamp_instance_1_level:
      <<: *customize
      friendly_name: Bookshelf Lamp
      icon: mdi:desk-lamp

    light.living_room_floor_lamp_instance_1_level:
      <<: *customize
      friendly_name: Floor Lamp
      icon: mdi:floor-lamp

    light.guest_closet_light_level:
      <<: *customize
      friendly_name: Guest Closet Light
      icon: mdi:lightbulb

    light.garage_light_level:
      <<: *customize
      friendly_name: Garage Storage Light
      icon: mdi:lightbulb

    light.dungeon_light_level:
      <<: *customize
      friendly_name: Dungeon Light
      icon: mdi:lightbulb

    ################################################
    ## Switches
    ################################################

    switch.basement_task_light:
      <<: *customize
      friendly_name: Basement Task Light
      icon: mdi:desk-lamp

################################################
## Automation *HOTFIX*
################################################

automation:
  - alias: "Fix Guest Closet Light"
    trigger:
      - platform: event
        event_type: call_service
        event_data:
          domain: "light"
          service: "turn_off"
          service_data:
              entity_id: light.guest_closet_light_level
      - platform: event
        event_type: call_service
        event_data:
          domain: "light"
          service: "turn_on"
          service_data:
              entity_id: light.guest_closet_light_level
    action:
      - delay: 2  # Waits 2 seconds
      - service: mqtt.publish
        data:
          topic: "OpenZWave/1/command/requestnodedynamic/"
          payload: '{ "node": 7}'
      - delay: 2  # Waits 2 seconds
      - service: mqtt.publish
        data:
          topic: "OpenZWave/1/command/requestnodedynamic/"
          payload: '{ "node": 7}'
      - delay: 2  # Waits 2 seconds
      - service: mqtt.publish
        data:
          topic: "OpenZWave/1/command/requestnodedynamic/"
          payload: '{ "node": 7}'

  - alias: "Fix Dungeon Light"
    trigger:
      - platform: event
        event_type: call_service
        event_data:
          domain: "light"
          service: "turn_off"
          service_data:
              entity_id: light.dungeon_light_level
      - platform: event
        event_type: call_service
        event_data:
          domain: "light"
          service: "turn_on"
          service_data:
              entity_id: light.dungeon_light_level
    action:
      - delay: 2  # Waits 5 seconds
      - service: mqtt.publish
        data:
          topic: "OpenZWave/1/command/requestnodedynamic/"
          payload: '{ "node": 9}'
      - delay: 2  # Waits 5 seconds
      - service: mqtt.publish
        data:
          topic: "OpenZWave/1/command/requestnodedynamic/"
          payload: '{ "node": 9}'
      - delay: 2  # Waits 5 seconds
      - service: mqtt.publish
        data:
          topic: "OpenZWave/1/command/requestnodedynamic/"
          payload: '{ "node": 9}'

  - alias: "Fix Garage Light"
    trigger:
      - platform: event
        event_type: call_service
        event_data:
          domain: "light"
          service: "turn_off"
          service_data:
              entity_id: light.garage_light_level
      - platform: event
        event_type: call_service
        event_data:
          domain: "light"
          service: "turn_on"
          service_data:
              entity_id: light.garage_light_level
    action:
      - delay: 2  # Waits 5 seconds
      - service: mqtt.publish
        data:
          topic: "OpenZWave/1/command/requestnodedynamic/"
          payload: '{ "node": 10}'
      - delay: 2  # Waits 5 seconds
      - service: mqtt.publish
        data:
          topic: "OpenZWave/1/command/requestnodedynamic/"
          payload: '{ "node": 10}'
      - delay: 2  # Waits 5 seconds
      - service: mqtt.publish
        data:
          topic: "OpenZWave/1/command/requestnodedynamic/"
          payload: '{ "node": 10}'

################################################
## Binary Sensor
################################################

binary_sensor:
  - platform: mqtt
    name: ozw_network_ready
    state_topic: OpenZWave/1/status/
    value_template: >
      {{ "on" if value_json.Status in ["driverAwakeNodesQueried", "driverAllNodesQueriedSomeDead", "driverAllNodesQueried"] else "off" }}
    json_attributes_topic: OpenZWave/1/status/
    delay_on: 5

################################################
## Light
################################################

light:
  - platform: switch
    name: Basement Task Light
    entity_id: switch.basement_task_light
